# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ws/sftools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ws/sftools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ws/sftools/CMakeFiles /home/ws/sftools/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ws/sftools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sfconvert

# Build rule for target.
sfconvert: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sfconvert
.PHONY : sfconvert

# fast build rule for target.
sfconvert/fast:
	$(MAKE) -f CMakeFiles/sfconvert.dir/build.make CMakeFiles/sfconvert.dir/build
.PHONY : sfconvert/fast

sfconvert.o: sfconvert.cpp.o
.PHONY : sfconvert.o

# target to build an object file
sfconvert.cpp.o:
	$(MAKE) -f CMakeFiles/sfconvert.dir/build.make CMakeFiles/sfconvert.dir/sfconvert.cpp.o
.PHONY : sfconvert.cpp.o

sfconvert.i: sfconvert.cpp.i
.PHONY : sfconvert.i

# target to preprocess a source file
sfconvert.cpp.i:
	$(MAKE) -f CMakeFiles/sfconvert.dir/build.make CMakeFiles/sfconvert.dir/sfconvert.cpp.i
.PHONY : sfconvert.cpp.i

sfconvert.s: sfconvert.cpp.s
.PHONY : sfconvert.s

# target to generate assembly for a file
sfconvert.cpp.s:
	$(MAKE) -f CMakeFiles/sfconvert.dir/build.make CMakeFiles/sfconvert.dir/sfconvert.cpp.s
.PHONY : sfconvert.cpp.s

sfont.o: sfont.cpp.o
.PHONY : sfont.o

# target to build an object file
sfont.cpp.o:
	$(MAKE) -f CMakeFiles/sfconvert.dir/build.make CMakeFiles/sfconvert.dir/sfont.cpp.o
.PHONY : sfont.cpp.o

sfont.i: sfont.cpp.i
.PHONY : sfont.i

# target to preprocess a source file
sfont.cpp.i:
	$(MAKE) -f CMakeFiles/sfconvert.dir/build.make CMakeFiles/sfconvert.dir/sfont.cpp.i
.PHONY : sfont.cpp.i

sfont.s: sfont.cpp.s
.PHONY : sfont.s

# target to generate assembly for a file
sfont.cpp.s:
	$(MAKE) -f CMakeFiles/sfconvert.dir/build.make CMakeFiles/sfconvert.dir/sfont.cpp.s
.PHONY : sfont.cpp.s

xml.o: xml.cpp.o
.PHONY : xml.o

# target to build an object file
xml.cpp.o:
	$(MAKE) -f CMakeFiles/sfconvert.dir/build.make CMakeFiles/sfconvert.dir/xml.cpp.o
.PHONY : xml.cpp.o

xml.i: xml.cpp.i
.PHONY : xml.i

# target to preprocess a source file
xml.cpp.i:
	$(MAKE) -f CMakeFiles/sfconvert.dir/build.make CMakeFiles/sfconvert.dir/xml.cpp.i
.PHONY : xml.cpp.i

xml.s: xml.cpp.s
.PHONY : xml.s

# target to generate assembly for a file
xml.cpp.s:
	$(MAKE) -f CMakeFiles/sfconvert.dir/build.make CMakeFiles/sfconvert.dir/xml.cpp.s
.PHONY : xml.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sfconvert"
	@echo "... sfconvert.o"
	@echo "... sfconvert.i"
	@echo "... sfconvert.s"
	@echo "... sfont.o"
	@echo "... sfont.i"
	@echo "... sfont.s"
	@echo "... xml.o"
	@echo "... xml.i"
	@echo "... xml.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

